### ISSUE TITLE
print where the actual report is

### ISSUE THREAD

**Issue by maxandersen** [igr/tdv#3]
I get this output:

```
Generating report for 0001-threaddump.txt.gz
Report for 0001-threaddump.txt.gz generated
```

...would be great if it would show it generated to out dir...and also which html file to use as index/to start with?

**Comment by igr** [comment]
FIxed in previous commit:

![CleanShot 2024-03-26 at 10 24 57@2x](https://github.com/igr/tdv/assets/2280001/d7a2ffc3-0e34-4843-8926-31528f1cba9c)
